export const SHOW_POST_LIST_SUCCESS = 'SHOW_POST_LIST_SUCCESS'
export const SHOW_POST_EDIT_SUCCESS = 'SHOW_POST_EDIT_SUCCESS'
export const SHOW_POST_CLOSED_EDIT_SUCCESS = 'SHOW_POST_CLOSED_EDIT_SUCCESS'
export const SHOW_POST_RECRUITMENT_SUCCESS = 'SHOW_POST_RECRUITMENT_SUCCESS'
export const SHOW_POST_CANCEL_RECRUITMENT_SUCCESS = 'SHOW_POST_RECRUITMENT_SUCCESS'


export const SHOW_POST_LIST_FAIL = 'SHOW_POST_LIST_FAIL'
export const SHOW_POST_EDIT_FAIL = 'SHOW_POST_EDIT_FAIL'
export const SHOW_POST_CLOSED_EDIT_FAIL = 'SHOW_POST_CLOSED_EDIT_FAIL'
export const SHOW_POST_RECRUITMENT_FAIL = 'SHOW_POST_RECRUITMENT_FAIL'
export const SHOW_POST_CANCEL_RECRUITMENT_FAIL = 'SHOW_POST_CANCEL_RECRUITMENT_FAIL'

export const SHOW_POST_RESET_SUCCESS = 'showPostResetSuccess'