export const SHOW_POST_LIST_SUCCESS = 'SHOW_POST_LIST_SUCCESS'
export const SHOW_POST_EDIT_SUCCESS = 'SHOW_POST_EDIT_SUCCESS'
export const SHOW_POST_CLOSED_EDIT_SUCCESS = 'SHOW_POST_CLOSED_EDIT_SUCCESS'
